"""
LinkedIn Agent Node -- Posts approved content drafts to LinkedIn.

For each approved draft ID, retrieves the LinkedIn hook from the draft
and posts it as a LinkedIn update. Results are stored in state.linkedin_posts.
"""

from typing import Any, Dict

from src.agents.orchestrator import AgentState
from src.tools.linkedin_tool import post_to_linkedin


async def linkedin_node(state: AgentState) -> AgentState:
    """
    Post the LinkedIn hook for each approved draft to LinkedIn.

    Skips unapproved drafts silently. Uses the linkedin_hook field
    generated by the content agent as the post body.

    Args:
        state: AgentState with content_drafts and approved_ids populated.

    Returns:
        Updated AgentState with linkedin_posts filled.
    """
    print(f"\n[linkedin_agent] >> Starting LinkedIn posting | cycle={state.cycle_id}")
    print(f"[linkedin_agent]   Approved IDs: {state.approved_ids}")

    if not state.approved_ids:
        print("[linkedin_agent] [WARN] No approved drafts -- skipping LinkedIn posting")
        return state

    # Build a lookup map from draft ID -> draft dict
    draft_map: Dict[str, Dict[str, Any]] = {
        d["id"]: d for d in state.content_drafts if "id" in d
    }

    for draft_id in state.approved_ids:
        draft = draft_map.get(draft_id)
        if not draft:
            state.errors.append(
                f"linkedin_node: Draft ID {draft_id} not found in content_drafts"
            )
            print(f"[linkedin_agent]   [FAIL] Draft {draft_id} not found -- skipping")
            continue

        linkedin_hook = draft.get("linkedin_hook", "")
        if not linkedin_hook:
            state.errors.append(f"linkedin_node: No linkedin_hook in draft {draft_id}")
            print(f"[linkedin_agent]   [FAIL] No LinkedIn hook in draft {draft_id} -- skipping")
            continue

        print(
            f"[linkedin_agent]   Posting draft "
            f"'{draft.get('title', draft_id)[:60]}'..."
        )

        try:
            result = await post_to_linkedin(text=linkedin_hook)
            post_record = {
                "draft_id": draft_id,
                "title": draft.get("title", ""),
                "linkedin_hook": linkedin_hook,
                **result,
            }
            state.linkedin_posts.append(post_record)

            if result.get("status") == "posted":
                print(f"[linkedin_agent]   [OK] Posted successfully for draft {draft_id}")
            else:
                print(
                    f"[linkedin_agent]   [FAIL] Post failed for draft {draft_id}: "
                    f"{result.get('error')}"
                )

        except Exception as e:
            state.errors.append(f"linkedin_node (draft {draft_id}): {str(e)}")
            print(f"[linkedin_agent]   [FAIL] Exception posting draft {draft_id}: {e}")

    print(
        f"[linkedin_agent] [OK] LinkedIn posting complete | "
        f"{len(state.linkedin_posts)} posts attempted"
    )
    return state
